In [5]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
x=np.arange(10).reshape(-1,1)
y=np.array([0,1,0,0,1,1,1,1,1,1])
model=LogisticRegression(solver='liblinear', C=10.0, random_state=0)
model.fit(x,y)
p_pred=model.predict_proba(x)
y_pred=model.predict(x)
score=model.score(x,y)
conf_m=confusion_matrix(y,y_pred)
report=classification_report(y,y_pred)
print('x:',x,sep='\n')
print('y:',y,sep='\n', end='n\n')
print('intercept:',model.intercept_)
print('coef', model.coef_,end='n\n')
print('p_pred',p_pred,sep='\n',end='n\n')
print('y_pred',y_pred,end='n\n')




x:
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
y:
[0 1 0 0 1 1 1 1 1 1]n
intercept: [-1.51632619]
coef [[0.703457]]n
p_pred
[[0.81999686 0.18000314]
 [0.69272057 0.30727943]
 [0.52732579 0.47267421]
 [0.35570732 0.64429268]
 [0.21458576 0.78541424]
 [0.11910229 0.88089771]
 [0.06271329 0.93728671]
 [0.03205032 0.96794968]
 [0.0161218  0.9838782 ]
 [0.00804372 0.99195628]]n
y_pred [0 0 0 1 1 1 1 1 1 1]n
